# Generated by Django 5.1.6 on 2025-02-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_discussionthread_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pediatrician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(default='Pediatrician', max_length=100)),
                ('experience', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pediatricians/')),
                ('description', models.TextField()),
            ],
        ),
    ]
